apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-22          # Deployment name 
spec:
  replicas: 3                   # Run 3 replicas
  selector:
    matchLabels:
      app: devops-app-22        # Label selector for pods
  template:
    metadata:
      labels:
        app: devops-app-22      # Label for pods
    spec:
      containers:
      - name: devops-app-container
        image: aaashish007/devops-app:1.0   # Your Docker Hub image
        ports:
        - containerPort: 8085          # Port inside container

---
#service yaml#
apiVersion: v1
kind: Service
metadata:
  name: devops-app-22-service
spec:
  type: NodePort
  selector:
    app: devops-app-22
  ports:
    - protocol: TCP
      port: 8085              # Service port
      targetPort: 8085        # Container port
      nodePort: 30085         # Node port to access externally